- name: Configure Kubernetes master
  hosts: localhost
  become: true
  tasks:
    # 1. Disable swap
    - name: Disable swap
      shell: |
        swapoff -a
        [ -f /etc/fstab ] && sed -i '/ swap / s/^/#/' /etc/fstab
      args:
        warn: false

    # 2. Install containerd without systemd
    - name: Install containerd
      apt:
        name: containerd
        state: present
        update_cache: yes

    - name: Create containerd config directory
      file:
        path: /etc/containerd
        state: directory
        mode: 0755

    - name: Generate default containerd config
      command: containerd config default > /etc/containerd/config.toml
      args:
        creates: /etc/containerd/config.toml

    - name: Configure containerd
      replace:
        path: /etc/containerd/config.toml
        regexp: 'sandbox_image = .*'
        replace: 'sandbox_image = "registry.k8s.io/pause:3.8"'

    - name: Start containerd
      shell: |
        mkdir -p /run/containerd
        containerd >/var/log/containerd.log 2>&1 &
        sleep 3  # Give containerd time to start
      args:
        warn: false

    # 3. Kernel modules and sysctl
    - name: Load kernel modules
      modprobe:
        name: "{{ item }}"
        state: present
      loop:
        - br_netfilter
        - overlay

    - name: Configure sysctl
      sysctl:
        name: "{{ item.key }}"
        value: "{{ item.value }}"
        state: present
        reload: yes
      with_items:
        - { key: 'net.bridge.bridge-nf-call-ip6tables', value: '1' }
        - { key: 'net.bridge.bridge-nf-call-iptables', value: '1' }

    # 4. Install Kubernetes components
    - name: Install prerequisites
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - software-properties-common
        state: present
        update_cache: yes

    - name: Add Kubernetes GPG key
      apt_key:
        url: https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key
        state: present

    - name: Add Kubernetes repository
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /"
        state: present
        filename: kubernetes

    - name: Install Kubernetes packages
      apt:
        name:
          - kubelet=1.28.15-1.1
          - kubeadm=1.28.15-1.1
          - kubectl=1.28.15-1.1
        state: present
        update_cache: yes

    - name: Hold Kubernetes packages
      command: apt-mark hold kubelet kubeadm kubectl

    # 5. Initialize cluster with retries
    - name: Initialize Kubernetes cluster
      shell: |
        kubeadm init \
          --pod-network-cidr=10.244.0.0/16 \
          --ignore-preflight-errors=Swap \
          --cri-socket=unix:///run/containerd/containerd.sock
      register: kubeadm_init
      retries: 3
      delay: 10
      until: kubeadm_init.rc == 0
      changed_when: false

  handlers:
    - name: restart containerd
      systemd:
        name: containerd
        state: restarted
