name: Kubernetes Cluster Setup (Vagrant + Ansible)

on: [push]

jobs:

  prepare-environment:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
      
      - name: Generate SSH key
        run: |
          mkdir -p ~/.ssh
          ssh-keygen -t rsa -f ~/.ssh/id_rsa -N ""
          chmod 600 ~/.ssh/id_rsa
          
      - name: Upload SSH key as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ssh-key
          path: ~/.ssh/id_rsa
  # Job for provisioning the master node
  setup-master:
    runs-on: [self-hosted, macos]
    needs: prepare-environment
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Install QEMU
      run: |
        arch -arm64 brew install qemu
    - name: Install VirtualBox and Vagrant dependencies
      run: |
        arch -x86_64 /usr/local/bin/brew install --cask virtualbox
        arch -x86_64 /usr/local/bin/brew install vagrant
        arch -x86_64 /usr/local/bin/brew install ansible

    - name: Download SSH key artifact
      uses: actions/download-artifact@v4
      with:
        name: ssh-key
        path: ~/.ssh/
    
    - name: Set permissions for SSH key
      run: chmod 600 ~/.ssh/id_rsa
    - name: Check VirtualBox network status
      run: |
        VBoxManage list hostonlyifs
        VBoxManage list vms
        VBoxManage list runningvms
        
    - name: Set up Vagrant environment for master node
      run: |
        vagrant destroy -f || true
        vagrant box add bento/ubuntu-16.04 --qemu virtualbox || true
        vagrant up --provider qemu k8s-master

    - name: Provision master node with Ansible
      run: |
        vagrant ssh k8s-master -c "sudo ansible-playbook /vagrant/kubernetes-setup/master-playbook.yml"

  # Job for provisioning worker nodes (parallel with the master node)
  setup-workers:
    runs-on: [self-hosted, macos]
    needs: setup-master  # Ensure workers start after the master is provisioned

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install VirtualBox and Vagrant dependencies
      run: |
        brew install virtualbox
        brew install vagrant
        brew install ansible

    - name: Set up Vagrant environment for worker nodes
      run: |
        vagrant destroy -f || true
        vagrant box add bento/ubuntu-16.04 --provider qemu || true
        vagrant up --provider qemu node-1 node-2

    - name: Provision worker nodes with Ansible
      run: |
        vagrant ssh node-1 -c "sudo ansible-playbook /vagrant/kubernetes-setup/node-playbook.yml"
        vagrant ssh node-2 -c "sudo ansible-playbook /vagrant/kubernetes-setup/node-playbook.yml"
