name: kubernetes-vagrant-cluster
on: [push]

jobs:
  # Run the vagrant-up workflow with your Kubernetes configuration
  run-kubernetes-cluster:
    uses: ./jfonseca1/vagrant-github-actions/.github/workflows/vagrant-up.yml
