name: Kubernetes Cluster Setup (Vagrant + Ansible)

on: [push]

jobs:
  # Job for provisioning the master node
  setup-master:
    runs-on: [self-hosted, macos]

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install VirtualBox and Vagrant dependencies
      run: |
        brew install virtualbox
        brew install vagrant
        brew install ansible

    - name: Set up Vagrant environment for master node
      run: |
        vagrant destroy -f || true
        vagrant box add bento/ubuntu-16.04 --provider virtualbox || true
        vagrant up --provider virtualbox k8s-master

    - name: Provision master node with Ansible
      run: |
        vagrant ssh k8s-master -c "sudo ansible-playbook /vagrant/kubernetes-setup/master-playbook.yml"

  # Job for provisioning worker nodes (parallel with the master node)
  setup-workers:
    runs-on: [self-hosted, macos]
    needs: setup-master  # Ensure workers start after the master is provisioned

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install VirtualBox and Vagrant dependencies
      run: |
        brew install virtualbox
        brew install vagrant
        brew install ansible

    - name: Set up Vagrant environment for worker nodes
      run: |
        vagrant destroy -f || true
        vagrant box add bento/ubuntu-16.04 --provider virtualbox || true
        vagrant up --provider virtualbox node-1 node-2

    - name: Provision worker nodes with Ansible
      run: |
        vagrant ssh node-1 -c "sudo ansible-playbook /vagrant/kubernetes-setup/node-playbook.yml"
        vagrant ssh node-2 -c "sudo ansible-playbook /vagrant/kubernetes-setup/node-playbook.yml"
