name: kubernetes-vagrant-cluster
on: [push]

jobs:
  prepare-environment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Generate SSH key
      run: |
        mkdir -p ~/.ssh
        ssh-keygen -t rsa -f ~/.ssh/id_rsa -N ""
        chmod 600 ~/.ssh/id_rsa
        
    - name: Upload SSH key as artifact
      uses: actions/upload-artifact@v4
      with:
        name: ssh-key
        path: ~/.ssh/id_rsa
        
  run-vagrant:
    needs: prepare-environment
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Download SSH key artifact
      uses: actions/download-artifact@v4
      with:
        name: ssh-key
        path: ~/.ssh/
    
    - name: Set permissions for SSH key
      run: chmod 600 ~/.ssh/id_rsa
    
    - name: Install Vagrant
      run: |
        wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
        echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
        sudo apt update && sudo apt install vagrant
    
    - name: Run Vagrant
      run: |
        vagrant box add bento/ubuntu-16.04 --provider virtualbox
        vagrant up
